### ISSUE TITLE
Support conventional commits

### ISSUE THREAD

**Issue by muyiwaolu** [muyiwaolu/dotfiles#3]
https://www.conventionalcommits.org/en/v1.0.0-beta.4/

- [x] Squash existing tree and tag it 1.0
- [x] Add a `bump version` action

```yml
name: Bump version
on:
  push:
    branches: ['main']
jobs:
  bump-version:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          release_branches: 'main'
          default_bump: false
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Create a GitHub release
        if: steps.tag_version.outputs.new_tag
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
```
